image: node:19-alpine

stages:
  - build
  - check

build:
  stage: build
  script:
    - yarn
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

lint:
  stage: check
  dependencies:
    - build
  needs: ['build']
  script:
    - yarn lint
