export const DUMMY_DATA = [
  {
    id: 0,
    title: 'Elegant Concrete Ball',
    productImage: 'https://picsum.photos/seed/J5gYVp/640/480',
    categories: 'Outdoors',
    price: 604,
    rating: 20,
    countries: 'Sweden',
    isFavorite: false,
    isSale: false,
  },
  {
    id: 1,
    title: 'Sleek Concrete Pizza',
    productImage: 'https://loremflickr.com/640/480?lock=3096160258490368',
    categories: 'Outdoors',
    price: 881,
    rating: 0,
    countries: 'Sweden',
    isFavorite: false,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    isSale: false,
  },
  {
    id: 2,
    title: 'Recycled Metal Soap',
    productImage: 'https://picsum.photos/seed/gDCSG/640/480',
    categories: 'Outdoors',
    price: 895,
    rating: 11,
    countries: 'Sweden',
    isFavorite: false,
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    isSale: false,
  },
  {
    id: 3,
    title: 'Bespoke Granite Car',
    productImage: 'https://picsum.photos/seed/tCp55m/640/480',
    categories: 'Outdoors',
    price: 851,
    rating: 37,
    countries: 'Sweden',
    isFavorite: false,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    isSale: false,
  },
  {
    id: 4,
    title: 'Gorgeous Cotton Fish',
    productImage: 'https://picsum.photos/seed/6VRkLkgi2/640/480',
    categories: 'Outdoors',
    price: 694,
    rating: 97,
    countries: 'Aruba',
    isFavorite: false,
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    isSale: false,
  },
  {
    id: 5,
    title: 'Bespoke Concrete Pants',
    productImage: 'https://picsum.photos/seed/QRQrrCls/640/480',
    categories: 'Films',
    price: 267,
    rating: 62,
    countries: 'Aruba',
    isFavorite: false,
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    isSale: false,
  },
  {
    id: 6,
    title: 'Small Cotton Sausages',
    productImage: 'https://picsum.photos/seed/D6kEzRqp0/640/480',
    categories: 'Outdoors',
    price: 542,
    rating: 13,
    countries: 'Canada',
    isFavorite: false,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    isSale: false,
  },
  {
    id: 7,
    title: 'Gorgeous Soft Shoes',
    productImage: 'https://picsum.photos/seed/Ni0ioFT/640/480',
    categories: 'Tools',
    price: 328,
    rating: 7,
    countries: 'Namibia',
    isFavorite: false,
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    isSale: false,
  },
  {
    id: 8,
    title: 'Tasty Wooden Towels',
    productImage: 'https://picsum.photos/seed/nhusFvQs4/640/480',
    categories: 'Tools',
    price: 57,
    rating: 24,
    countries: 'Russian Federation',
    isFavorite: false,
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    isSale: false,
  },
  {
    id: 9,
    title: 'Modern Cotton Bacon',
    productImage: 'https://picsum.photos/seed/7XFNo2sc/640/480',
    categories: 'Tools',
    price: 536,
    rating: 89,
    countries: 'Poland',
    isFavorite: false,
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    isSale: false,
  },
  {
    id: 10,
    title: 'Rustic Frozen Computer',
    productImage: 'https://picsum.photos/seed/2Ydsp/640/480',
    categories: 'Films',
    price: 226,
    rating: 23,
    countries: 'Comoros',
    isFavorite: false,
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    isSale: false,
  },
]
